config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :notes
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  resources :users
  resources :static_pages do
  	collection do
		  get :new_consumer
		  post :create_consumer
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @users = User.all.consumer
    end
  end

  def new_consumer
    @user = User.new
  end

  def create_consumer
    current_user.consumers.create(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params[:user][:role] = 2
  	params.require(:user).permit(:email, :password, :approved, :role, :provider_id, :uid)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
	<% if current_user.admin? %>
		<p> I am admin </p>
	<% elsif current_user.provider? %>
		<p> I am provider </p>
		<%= link_to 'Create Consumer', new_consumer_static_pages_path %><br/><br/><br/>
		<% @users.all.each do |user| %>
			<%= link_to user.email, user_path(user) %><br/>
		<% end %>
	<% else %>
		<h2>Notes</h2>
		<% current_user.notes.each do |note| %>
			<%= note.service %><br/>
		<% end %><br/><br/><br/>
		<h2>Orders</h2>
		<% current_user.orders.each do |order| %>
			<%= order.name %><br/>
		<% end %>
	<% end %><br/><br/><br/>
	<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Log In", new_user_session_path %>
<% end %>

app/views/static_pages/new_consumer.html.erb
<ul class="form_ul">

<%= form_for @user, url: create_consumer_static_pages_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this med from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <li>
    <%= f.label :email, 'email' %><br/>
    <%= f.text_field :email, autofocus: true,  id: 'text_field', type: 'text', input: "webkit-speech" %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </li>
  <li>
    <%= f.label :approved %><br/>
    <%= f.check_box :approved %>
  </li>
  <li >
    <%= f.submit class: 'btn' %>
  </li>
<% end %>
</ul>