config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :notes
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'static_pages#home'

  resources :users
  resources :static_pages do
  	collection do
		  get :new_consumer
		  post :create_consumer
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable, :timeoutable, :omniauthable, :omniauth_providers => [:google_oauth2]

  enum role: %w(provider admin consumer)

  has_many :consumers, class_name: "User",
                       foreign_key: "provider_id"

  belongs_to :provider, class_name: "User"

  has_many :orders, dependent: :destroy
  has_many :notes, dependent: :destroy

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
   if !approved?
     :not_approved
   else
     super # Use whatever other message
   end
  end

  def self.send_reset_password_instructions(attributes={})
    recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    if !recoverable.approved?
      recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
    elsif recoverable.persisted?
      recoverable.send_reset_password_instructions
    end
    recoverable
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.auth_provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.provider = user
      #user.approved = true
      #user.save!
      user.save!(validate: false)
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
 
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user, notice: "Signed in!"
    else
      redirect_to new_user_registration_url
    end
  end



  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

	def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    errors = User.create(user_params).errors
    respond_to do |format|
      if errors.one? && errors[:provider].present?
      	@user.save(validate: false)
        @user.update_attributes(provider: @user)
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
      	format.html { redirect_to 'new' }
      	format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :approved, :provider_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [ :edit, :update, :destroy]

    def index
      @users = User.all
    end

    def edit

    end

    def show
      @user = User.find(params[:id])
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'user was successfully updated.' }
          format.json { render :index, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    private
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :provider, :uid, :encrypted_password, :reset_password_token,
      :reset_password_sent_at, :remember_created_at, :sign_in_count, :current_sign_in_at,
      :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :failed_attempts,
      :unlock_token, :locked_at, :approved, :id)
    end
end

app/views/users/_form.html.erb
<ul class="form_ul">

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this med from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <li>
    <%= f.label :email, 'email' %><br/>
    <%= f.text_field :email, autofocus: true,  id: 'text_field', type: 'text', input: "webkit-speech" %>
  </li>
  <li>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </li>
  <li>
    <%= f.label :approved %><br/>
    <%= f.check_box :approved %>
  </li>
  <li >
    <%= f.submit class: 'btn' %>
  </li>
<% end %>
</ul>

app/views/users/edit.html.erb
<h1 id="h3">Editing: <%= @user.email   %></h1>

<%= render 'form' %>
<div id="link">
<%= link_to 'Cancel', users_path %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>


<%= link_to "All Users", :action => "index" %>
|
<%= link_to "Users awaiting approval", :action => "index", :approved => "false" %>

<%= link_to 'Create Consumer', new_user_path %>
<table>
<% @users.each do |user| %>
  <tr>
    <td>
      user.email
    </td>
    <td>
      user.approved
    </td>
    <td>
      <%= link_to "edit", edit_user_path(user) %>
    </td>
  </tr>

</table>
<% end %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="index">
<nav>
  <%= link_to("all users", users_path) %>
</nav>

<article>
  <header>
    <h2 id="h3"><%= @user.email %> | <%= @user.created_at.to_s(:long) %></h2>
  </header>
  <h3>email:</h3>
  <p>
    <%= @user.email %>
  </p>
  <h3>approved:</h3>
  <p>
    <%= @user.approved %>
  </p>
  <h3>id:</h3>
  <p>
    <%= @user.id %>
  </p>

</article>
</div>


<%= link_to 'New Order', new_order_path(user_id: @user) %><br/><br/><br/>
<%= link_to 'New Note', new_note_path(user_id: @user) %>